replicaCount: 1

image:
  repository: 10.108.168.228:8083/getting-started
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080 

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: hello-world.info
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}