replicaCount: 1

image:
  repository: your-nexus-url/repository/docker-repo/getting-started
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: localhost


resources: {}