replicaCount: 1

image:
  repository: http://localhost:8081/repository/docker-local/getting-started
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: localhost


resources: {}