replicaCount: 1

image:
  repository: nexus-docker.nexus.svc.cluster.local:8083/getting-started
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: localhost

serviceAccount:
  create: true  
  name: ""      

autoscaling:
  enabled: false  
  minReplicas: 1  
  maxReplicas: 5  
  targetCPUUtilizationPercentage: 80  


resources: {}