replicaCount: 1

image:
  repository: 10.108.168.228:8083/getting-started
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hosts:
    - host: localhost    

autoscaling:
  enabled: false  
  minReplicas: 1  
  maxReplicas: 5  
  targetCPUUtilizationPercentage: 80  


resources: {}