replicaCount: 1

image:
  repository: nexus.local/getting-started
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

serviceAccount: 
  name: "jenkins"      

autoscaling:
  enabled: false  
  minReplicas: 1  
  maxReplicas: 5  
  targetCPUUtilizationPercentage: 80  


resources: {}