apiVersion: v1
kind: Service
metadata:
  name: nexus-docker
  namespace: nexus
spec:
  selector:
    app.kubernetes.io/instance: my-nexus
    app.kubernetes.io/name: nexus-repository-manager
  ports:
    - name: docker
      port: 8083
      targetPort: 8083
  type: ClusterIP

